### ISSUE TITLE
Do not block PUT and DELETE requests

### ISSUE THREAD

**Issue by Jop-V** [webpkg/ngxpkg#1]
In newly generated configs, this:

    if ($request_method !~ ^(GET|HEAD|POST|OPTIONS)$ ) {

needs to be this:

    if ($request_method !~ ^(GET|HEAD|POST|OPTIONS|PUT|DELETE)$ ) {

Took me a bit to discover why my site's admin panel didn't work.

**Comment by afxcn** [comment]
Thank you @Jop-V, fixed it.

And you can change the site.conf file at ~/.config/ngxpkg/rc/site.conf, it will only download from rc.ngxpkg.com one time.
