### ISSUE TITLE
Already registered

### ISSUE THREAD

**Issue by andrewmiller1** [webpkg/ngxpkg#3]
Hello,

Apologies for being a noob here. I used acme.sh but could not for the life of me figure out how to throw the certificates in just the right shape and form for OCSP to function when turned on. I saw ngxpkg simply provisions a certificate for OCSP for you. My mouth drooled.

However, since my domain is already registered with acme, I cannot use ngxpkg's `new` function. I have all my registration information down to the account key. Is there a way to use this in ngxpkg to provision my domain's certificates?

**Comment by afxcn** [comment]
i think do it by manual is more easy.

    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /opt/local/www/ngxpkg.com/conf/ocsp.pem;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

ocsp.pem is intermediates ca + root ca.

Reference Links:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by andrewmiller1** [comment]
Ah it makes sense now

> ocsp.pem is intermediates ca + root ca

That's what I needed. Thanks!
